name: Convert resume to PDF

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            # - name: Setup LaTeX
            #   uses: dante-ev/action-texlive@v2

            - name: Install pdflatex
              run: sudo apt-get install texlive-latex-base

            - name: Install pandoc
              run: sudo apt-get install -y pandoc

            - name: Convert Markdown to PDF
              run: pandoc my-resume.md -o my-resume.pdf

            - name: Upload PDF artifact
              uses: actions/upload-artifact@v2
              with:
                  name: my-resume-pdf
                  path: my-resume.pdf

            - name: Download PDF artifact
              uses: actions/download-artifact@v2
              with:
                  name: my-resume-pdf

            - name: Move PDF to main directory
              run: mv ${{ github.workspace }}/my-resume.pdf ${{ github.workspace }}/../my-resume.pdf

            - name: Print PDF directory to a file
              run: echo ${{ github.workspace }}/../my-resume.pdf > path.txt
